name: Secure Workflow
on:
  pull_request_target:
    branches: master
  workflow_dispatch:
permissions: read-all
jobs:
  Safe-Job:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Run scripts from code - Master
      run: chmod +x ./scripts/index.sh && ./scripts/index.sh
