name: Secure Workflow

on:
  pull_request:
    branches: master

permissions: read-all

jobs:
  Safe-Job:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Checking downloaded repo
      run: echo 'Hello from Fork'
